sensor:

  # Header Outdoor Temperate
  - platform: homeassistant
    entity_id: sensor.cabinet_temperature
    id: cabinet_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d째 / %d째"
            args: [ '(int)round(id(outside_temperature).state)', '(int)round(x)' ]

  - platform: homeassistant
    entity_id: sensor.outside_temperature
    id: outside_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d째 / %d째"
            args: [ '(int)round(x)', '(int)round(id(cabinet_temperature).state)' ]



binary_sensor:

  # Office Evening Scene
  - platform: homeassistant
    id: office_scene_evening
    entity_id: binary_sensor.office_scene_evening
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_evening_button
          state:
            checked: !lambda return x;

  # Office Calls Scene
  - platform: homeassistant
    id: office_scene_desk_call
    entity_id: binary_sensor.office_scene_desk_call
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_calls_button
          state:
            checked: !lambda return x;

  # Office Features Scene
  - platform: homeassistant
    id: office_scene_features
    entity_id: binary_sensor.office_scene_features
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_features_button
          state:
            checked: !lambda return x;

  # Office Storage Light
  - platform: homeassistant
    id: office_storage
    entity_id: light.office_storage
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_storage_light_button
          state:
            checked: !lambda return x;

  # 3d Printer
  - platform: homeassistant
    id: office_3d_printer_power
    entity_id: switch.office_3d_printer_power
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: printer_power_button
          state:
            checked: !lambda return x;

  # 3d Printer Lights
  - platform: homeassistant
    id: office_3d_printer_lights
    entity_id: switch.office_3d_printer_lights
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: printer_lights_button
          state:
            checked: !lambda return x;

  # Lenovo Server
  - platform: homeassistant
    id: lenovo_power
    entity_id: switch.lenovo_power
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: lenovo_power_button
          state:
            checked: !lambda return x;

  # Office Aircon
  - platform: homeassistant
    id: office_air_conditioner
    entity_id: switch.office_air_conditioner
    #id: climate.cabinet_ac
    #entity_id: climate.cabinet_ac
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_aircon_button
          state:
            checked: !lambda return x;
